function opponents = createOpponentFleet(track, params)
% createOpponentFleet
% 여러 대의 상대 차량을 한 번에 생성하는 함수

arguments
    track struct
    params struct
end

numOpponents = params.numOpponents;

% 첫 번째 opponent를 먼저 생성해서 구조체 필드 형태를 확정
opponents(1,1) = createOpponentCar( ...
    1, ...
    params.names(1), ...
    params.initialS(1), ...
    params.initialD(1), ...
    params.speed(1), ...
    params.behaviorType(1), ...
    track);

for i = 2:numOpponents
    opponents(i,1) = createOpponentCar( ...
        i, ...
        params.names(i), ...
        params.initialS(i), ...
        params.initialD(i), ...
        params.speed(i), ...
        params.behaviorType(i), ...
        track);
end

end